const FETCH_USER = 'FETCH_USER';
const LOGIN = 'LOGIN';
const SIGNUP = 'SIGNUP';
const LOGOUT = 'LOGOUT';
const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
const CATEGORY_PRODUCTS = 'CATEGORY_PRODUCTS'
const CATEGORIES = 'CATEGORIES'
const ALL_PRODUCTS = 'ALL_PRODUCTS'
const ADD_TO_CART = 'ADD_TO_CART';
const DELETE_FROM_CART = 'DELETE_FROM_CART';
const UPDATE_CART_ITEM = 'UPDATE_CART_ITEM';
const TRANSACTION = 'TRANSACTION';
 
export {FETCH_USER, LOGIN, SIGNUP, LOGOUT, FETCH_PRODUCTS, CATEGORY_PRODUCTS, CATEGORIES, ALL_PRODUCTS, ADD_TO_CART, DELETE_FROM_CART, UPDATE_CART_ITEM, TRANSACTION, };